module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "app-muted": "var(--app-muted)",
        "app-primary": "var(--app-primary)",
        "gray-60": "var(--gray-60)",
        "gray-80": "var(--gray-80)",
        lightmodedangerdanger: "var(--lightmodedangerdanger)",
        "lightmodegreygrey-200": "var(--lightmodegreygrey-200)",
        "lightmodegreygrey-300": "var(--lightmodegreygrey-300)",
        "lightmodegreygrey-400": "var(--lightmodegreygrey-400)",
        "lightmodegreygrey-500": "var(--lightmodegreygrey-500)",
        "lightmodegreygrey-600": "var(--lightmodegreygrey-600)",
        "lightmodegreygrey-700": "var(--lightmodegreygrey-700)",
        "lightmodegreygrey-800": "var(--lightmodegreygrey-800)",
        "lightmodegreygrey-900": "var(--lightmodegreygrey-900)",
        lightmodelightlight: "var(--lightmodelightlight)",
        lightmodeorangeorange: "var(--lightmodeorangeorange)",
        lightmodesuccesssuccess: "var(--lightmodesuccesssuccess)",
        "lightmodesuccesssuccess-active":
          "var(--lightmodesuccesssuccess-active)",
        "lightmodesuccesssuccess-clarity-20":
          "var(--lightmodesuccesssuccess-clarity-20)",
        "lightmodesuccesssuccess-light": "var(--lightmodesuccesssuccess-light)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-b-10-10-400": "var(--body-b-10-10-400-font-family)",
        "body-b-11-12-400": "var(--body-b-11-12-400-font-family)",
        "body-b-11-12-500": "var(--body-b-11-12-500-font-family)",
        "body-b-12-12-400": "var(--body-b-12-12-400-font-family)",
        "body-b-12-12-500": "var(--body-b-12-12-500-font-family)",
        "body-b-13-14-400": "var(--body-b-13-14-400-font-family)",
        "body-b-13-14-500": "var(--body-b-13-14-500-font-family)",
        "body-b-13-20-400": "var(--body-b-13-20-400-font-family)",
        "body-b-14-14-400": "var(--body-b-14-14-400-font-family)",
        "body-b-14-14-500": "var(--body-b-14-14-500-font-family)",
        "body-b-14-22-400": "var(--body-b-14-22-400-font-family)",
        "body-b-14-22-500": "var(--body-b-14-22-500-font-family)",
        "body-b-15-16-400": "var(--body-b-15-16-400-font-family)",
        "body-b-15-24-400": "var(--body-b-15-24-400-font-family)",
        "body-b-16-16-400": "var(--body-b-16-16-400-font-family)",
        "body-b-16-16-500": "var(--body-b-16-16-500-font-family)",
        "body-b-16-25-600": "var(--body-b-16-25-600-font-family)",
        "body-b-18-25-600": "var(--body-b-18-25-600-font-family)",
        "heading-h-24-24-600": "var(--heading-h-24-24-600-font-family)",
        "heading-h-26-26-600": "var(--heading-h-26-26-600-font-family)",
        "heading-h-30-30-600": "var(--heading-h-30-30-600-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "widget-shadow-intence": "var(--widget-shadow-intence)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
